const quotes = [
  "The end is near.",
  "You're strong. But I could snap my fingers, and you'd all cease to exist.",
  "Fun isn't something one considers when balancing the universe. But this… does put a smile on my face.",
  "You have my respect, Stark. When I'm done, half of humanity will still be alive. I hope they remember you.",
  "Perfectly balanced, as all things should be.",
  "I hope they remember you.",
  "You should have gone for the head.",
  "I know what it's like to lose. To feel so desperately that you're right, yet to fail nonetheless. Dread it. Run from it. Destiny still arrives. Or should I say, I have.",
  "You're a great fighter, Gamora. Come. Let me help you.",
  "Going to bed hungry. Scrounging for scraps. Your planet was on the brink of collapse. I was the one who stopped that. You know what's happened since then? The children born have known nothing but full bellies and clear skies. It's a paradise.",
  "I'm the only one who knows that. At least I'm the only who has the will to act on it. For a time, you had that same will. As you fought by my side, daughter.",
  "I ignored my destiny once, I can not do that again. Even for you. I'm sorry little one.",
  "With all six stones, I can simply snap my fingers, and they would all cease to exist. I call that mercy.",
  "Your optimism is misplaced, Asgardian.",
  "You're strong. Me… You're generous. Me… But I never taught you to lie. That's why you're so bad at it. Where is the Soul Stone?",
  "You should choose your words wisely",
  "The hardest choices require the strongest wills.",
  "Fine. I'll do it myself.",
  "Well, if you consider failure experience.",
  "No resurrections this time.",
  "Little one, it's a simple calculus. This universe is finite. Its resources, finite. If life is left unchecked, life will cease to exist. It needs correction.",
  "I am disappointed. But not because you didn't find it. But because you did, and you lied.",
  "All that for a drop of blood.",
  "You're not the only one cursed with knowledge.",
  "Today, I lost more than you can know. But now is no time to mourn. Now is no time at all.",
  "You could not live with your own failure. And where did that bring you? Back to me.",
  "I am... inevitable.",
  "I don't even know who you are.",
  "I will shred this universe down to it's last atom and then, with the stones you've collected for me, create a new one. It is not what is lost but only what it is been given... a grateful universe.",
  "I thought by eliminating half of life, the other half would thrive, but you have shown me... that's impossible. As long as there are those that remember what was, there will always be those, that are unable to accept what can be. They will resist.",
  "Thank you, daughter. Perhaps I treated you too harshly.",
  "I'm thankful. Because now I know what I must do.",
  "They'll never know it. Because you won't be alive to tell them.",
  "A small price to pay for salvation.",
  "I used the stones to destroy the stones. And it nearly killed me. But the work is done, it always will be. I am inevitable.",
  "The universe required correction. After that, the stones served no purpose beyond temptation.",
  "You should choose your words more carefully.",
];

module.exports = quotes.map((quote, idx) => ({ id: idx + 1, quote }));